git clone https://github.com/hackedteam/core-android-audiocapture.git
git clone https://github.com/hackedteam/core-android.git
git clone https://github.com/hackedteam/core-android-market.git
git clone https://github.com/hackedteam/core-android-native.git
git clone https://github.com/hackedteam/core-blackberry.git
git clone https://github.com/hackedteam/core-ios.git
git clone https://github.com/hackedteam/core-linux.git
git clone https://github.com/hackedteam/core-macos.git
git clone https://github.com/hackedteam/core-packer.git
git clone https://github.com/hackedteam/core-symbian.git
git clone https://github.com/hackedteam/core-win32.git
git clone https://github.com/hackedteam/core-win64.git
git clone https://github.com/hackedteam/core-winmobile.git
git clone https://github.com/hackedteam/core-winphone.git
git clone https://github.com/hackedteam/driver-macos.git
git clone https://github.com/hackedteam/driver-win32.git
git clone https://github.com/hackedteam/driver-win64.git
git clone https://github.com/hackedteam/fuzzer-android.git
git clone https://github.com/hackedteam/fuzzer-windows.git
git clone https://github.com/hackedteam/gitosis-admin.git
git clone https://github.com/hackedteam/poc-x.git
git clone https://github.com/hackedteam/rcs-anonymizer.git
git clone https://github.com/hackedteam/rcs-anonymizer-old.git
git clone https://github.com/hackedteam/rcs-backdoor.git
git clone https://github.com/hackedteam/rcs-collector.git
git clone https://github.com/hackedteam/rcs-common.git
git clone https://github.com/hackedteam/rcs-console.git
git clone https://github.com/hackedteam/rcs-console-library.git
git clone https://github.com/hackedteam/rcs-console-mobile.git
git clone https://github.com/hackedteam/rcs-db-ext.git
git clone https://github.com/hackedteam/scout-win.git
git clone https://github.com/hackedteam/soldier-win.git
git clone https://github.com/hackedteam/test-av2.git
git clone https://github.com/hackedteam/test-av.git
git clone https://github.com/hackedteam/vector-applet.git
git clone https://github.com/hackedteam/vector-default.git
git clone https://github.com/hackedteam/vector-dropper.git
git clone https://github.com/hackedteam/vector-edk.git
git clone https://github.com/hackedteam/vector-exploit.git
git clone https://github.com/hackedteam/vector-ipa.git
git clone https://github.com/hackedteam/vector-macos-root.git
git clone https://github.com/hackedteam/vector-ni.git
git clone https://github.com/hackedteam/vector-offline2.git
git clone https://github.com/hackedteam/vector-offline.git
git clone https://github.com/hackedteam/vector-recover.git
git clone https://github.com/hackedteam/vector-rmi.git
git clone https://github.com/hackedteam/vector-silent.git